name: Deploy to aws

on:
  push:
    branches:
      - "aris"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: connect to ec2 aws
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd be-node/
            git pull origin master
            docker stop be-container-2
            docker rm be-container-2
            docker rmi be-node-2
            docker build -t be-node-2 .
            docker run -d -p 3001:3000 -e SERVER_PORT=${{ secrets.SERVER_PORT }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} -e ENDPOINT_URL=${{ secrets.ENDPOINT_URL }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e SHADOW_DATABASE_URL=${{ secrets.SHADOW_DATABASE_URL }} --name be-container-2 be-node-2