name: Deploy to aws

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: connect to ec2 aws
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd be-node/
            git pull origin master
            npm install
            npx prisma generate
            npx prisma migrate dev
            npx prisma db push
            npm run build
            pm2 restart be-node